AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shorter
  url-shorter #magic___^_^___line Sample SAM Template


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.10

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-url
      AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  PostUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: url_shorter.url_shortener
      Description: Handler for Url Post
      Environment:
        Variables:
          URL_TABLE: !Ref UrlTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref UrlTable
      Tags:
        Stack: !Sub "${AWS::StackName}"
      Events:
        PostUrl:
          Type: Api
          Properties:
            Path: /createSecret
            Method: post
            RestApiId: !Ref RestAPI
  

  GetByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_by_id.lambda_handler
      Description: Handler for get by id
      Environment:
        Variables:
          URL_TABLE: !Ref UrlTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref UrlTable
      Tags:
        Stack: !Sub "${AWS::StackName}"
      Events:
        PostUrl:
          Type: Api
          Properties:
            Path: /getbyuserid/{id}
            Method: get
            RestApiId: !Ref RestAPI

  GetByShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_by_short_url.lambda_handler
      Description: Handler for get by short url
      Environment:
        Variables:
          URL_TABLE: !Ref UrlTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref UrlTable
      Tags:
        Stack: !Sub "${AWS::StackName}"
      Events:
        PostUrl:
          Type: Api
          Properties:
            Path: /getbyshorturl/{userid}/{shorturl}
            Method: get
            RestApiId: !Ref RestAPI

  CreateShorturlByUseridFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create_shorturl_by_userid.lambda_handler
      Description: Handler for add url to existing user
      Environment:
        Variables:
          URL_TABLE: !Ref UrlTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref UrlTable
      Tags:
        Stack: !Sub "${AWS::StackName}"
      Events:
        PostUrl:
          Type: Api
          Properties:
            Path: /addurl/{userid}
            Method: post
            RestApiId: !Ref RestAPI


  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Tags:
        Name: !Sub "${AWS::StackName}-API"
        Stack: !Sub "${AWS::StackName}"


Outputs:
  PostUrlFunction:
    Description: API Gateway endpoint URL for Prod stage for Post Url function
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/createSecret"

  GetByIdFunction:
    Description: API Gateway endpoint URL for Prod stage for Get By User Id Function
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/getbyuserid/{id}"

  GetByShortUrlFunction:
    Description: API Gateway endpoint URL for Prod stage for Get By Short Url Function
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/getbyshorturl/{userid}/{shorturl}"
  
  CreateShorturlByUseridFunction:
    Description: API Gateway endpoint URL for Prod stage for add url to existing user
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/addurl/{userid}"

  RestAPI:
    Description: RESTAPI
    Value: !Ref RestAPI

  UrlTable:
    Description: DynamoDB Table
    Value: !Ref UrlTable
